[book]
title = "Citadel Documentation"
author = "Team Subgraph"
description = "Documentation on installing, configuring, and using Citadel by Subgraph."
multilingual = false
src = "markdown"

[build]
build-dir = "book"
create-missing = false
theme = "citadel"

[output.html]
curly-quotes = false
additional-css = ["custom.css"]
no-section-label = true

[output.html.search]
enable = true
searcher = "./path/to/searcher"
limit-results = 15
teaser-word-count = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
